<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="58487" started-at="2019-01-30T15:23:00Z" finished-at="2019-01-30T15:23:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58487" started-at="2019-01-30T15:23:00Z" finished-at="2019-01-30T15:23:58Z">
      <class name="com.wibmo.KYC.tests.KYC_002">
        <test-method status="PASS" signature="initializeReports()[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b]" name="initializeReports" is-config="true" duration-ms="2436" started-at="2019-01-30T20:52:57Z" finished-at="2019-01-30T20:53:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeReports -->
        <test-method status="PASS" signature="testStart(java.lang.reflect.Method)[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b]" name="testStart" is-config="true" duration-ms="31" started-at="2019-01-30T20:53:00Z" finished-at="2019-01-30T20:53:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.wibmo.KYC.tests.KYC_002.KYC_002()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStart -->
        <test-method status="FAIL" signature="KYC_002()[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b]" name="KYC_002" duration-ms="31365" started-at="2019-01-30T20:53:00Z" finished-at="2019-01-30T20:53:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid response : {"code":400,"message":"User already registered!"} expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid response : {"code":400,"message":"User already registered!"} expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.wibmo.API.RegisterOfflineAPI.offlineReg(RegisterOfflineAPI.java:43)
	at com.wibmo.API.RegisterOfflineAPI.offlineRegistration(RegisterOfflineAPI.java:16)
	at com.wibmo.KYC.tests.KYC_002.KYC_002(KYC_002.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KYC_002 -->
        <test-method status="PASS" signature="updateResults(org.testng.ITestResult)[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b]" name="updateResults" is-config="true" duration-ms="2157" started-at="2019-01-30T20:53:31Z" finished-at="2019-01-30T20:53:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=KYC_002 status=FAILURE method=KYC_002.KYC_002()[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateResults -->
        <test-method status="FAIL" signature="deleteUser()[pri:0, instance:com.wibmo.KYC.tests.KYC_002@6c7a164b]" name="deleteUser" is-config="true" duration-ms="24746" started-at="2019-01-30T20:53:33Z" finished-at="2019-01-30T20:53:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error connecting to DB 
08S01]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error connecting to DB 
08S01
	at org.testng.Assert.fail(Assert.java:93)
	at library.DB.stmt(DB.java:53)
	at library.DB.update(DB.java:76)
	at library.DB.deleteUser(DB.java:370)
	at com.wibmo.KYC.tests.KYC_002.deleteUser(KYC_002.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:958)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
      </class> <!-- com.wibmo.KYC.tests.KYC_002 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
